# Generated by Django 2.0.1 on 2018-01-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resourcesmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelTatble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, unique=True, verbose_name='姓名')),
                ('Phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='电话')),
                ('QQNunmber', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='QQ号')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
            ],
            options={
                'verbose_name': '联系人信息',
                'verbose_name_plural': '联系人信息',
                'ordering': ['Name'],
            },
        ),
    ]
