# Generated by Django 2.0.1 on 2018-01-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resourcesmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CabinetName', models.CharField(max_length=40, verbose_name='机柜名称')),
                ('CabinetSize', models.CharField(max_length=40, verbose_name='机柜高度')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机柜信息',
                'verbose_name_plural': '机柜信息',
            },
        ),
        migrations.CreateModel(
            name='ComputerRoomTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComputerRoomName', models.CharField(max_length=40, verbose_name='机房名称')),
                ('ComputerRoomAddress', models.CharField(max_length=200, verbose_name='机房位置')),
                ('ComputerRoomPhone', models.CharField(max_length=40, verbose_name='联系电话')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机房信息',
                'verbose_name_plural': '机房信息',
            },
        ),
        migrations.CreateModel(
            name='EquipmentManufacturersTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManufacturersName', models.CharField(max_length=40, verbose_name='厂商名称')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备厂商',
                'verbose_name_plural': '设备厂商',
            },
        ),
        migrations.CreateModel(
            name='NetworkMachineTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NetworkMachineName', models.CharField(max_length=100, verbose_name='机器名')),
                ('NetworkMachineType', models.CharField(max_length=100, verbose_name='机器型号')),
                ('PortSize', models.CharField(max_length=100, verbose_name='端口数')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('CabinetName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerRoomManagerment.CabinetTable')),
            ],
            options={
                'verbose_name': '网络设备信息',
                'verbose_name_plural': '网络设备信息',
            },
        ),
        migrations.CreateModel(
            name='ServerMachineTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManufacturersType', models.CharField(max_length=100, verbose_name='机器型号')),
                ('SNNumber', models.CharField(max_length=100, verbose_name='SN号')),
                ('DiskType', models.CharField(max_length=20, verbose_name='硬盘类型')),
                ('DiskSize', models.CharField(max_length=20, verbose_name='硬盘大小')),
                ('RAMSize', models.CharField(max_length=20, verbose_name='内存大小')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
                ('CabinetName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerRoomManagerment.CabinetTable')),
                ('ManufacturersName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerRoomManagerment.EquipmentManufacturersTable')),
                ('NetworkMachineName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerRoomManagerment.NetworkMachineTable')),
            ],
            options={
                'verbose_name': '服务器信息',
                'verbose_name_plural': '服务器信息',
            },
        ),
        migrations.AddField(
            model_name='cabinettable',
            name='ComputerRoomName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComputerRoomManagerment.ComputerRoomTable'),
        ),
    ]
