# Generated by Django 2.0.1 on 2018-01-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resourcesmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktoSounceExportTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddressSegment', models.CharField(max_length=40, unique=True, verbose_name='回源地址段')),
                ('Province', models.CharField(max_length=40, verbose_name='省份')),
                ('City', models.CharField(max_length=40, verbose_name='城市')),
                ('BackboneTransmission', models.CharField(blank=True, max_length=40, null=True, verbose_name='骨干传输')),
                ('ASNumber', models.IntegerField(blank=True, null=True, verbose_name='AS号')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '回源出口表',
                'verbose_name_plural': '回源出口表',
                'ordering': ['AddressSegment'],
            },
        ),
        migrations.CreateModel(
            name='CDNmanagementIpTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ManagementIp', models.CharField(max_length=40, verbose_name='CDN管理IP')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
            ],
            options={
                'verbose_name': 'cp管理地址表',
                'verbose_name_plural': 'cp管理地址表',
                'ordering': ['ManagementIp'],
            },
        ),
        migrations.CreateModel(
            name='InternetResoucesTatble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InternetAddsegment', models.CharField(max_length=40, verbose_name='互联IP段')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
            ],
            options={
                'verbose_name': '互联资源列表',
                'verbose_name_plural': '互联资源列表',
                'ordering': ['InternetAddsegment'],
            },
        ),
        migrations.CreateModel(
            name='NetTypeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NetType', models.CharField(max_length=40, verbose_name='网络类型')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网络类型表',
                'verbose_name_plural': '网络类型表',
            },
        ),
        migrations.CreateModel(
            name='ServerIPTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerAddress', models.CharField(max_length=40, verbose_name='服务ip')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('CDN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resourcesmanagement.CDNTable')),
            ],
            options={
                'verbose_name': '具体服务表',
                'verbose_name_plural': '具体服务表',
            },
        ),
        migrations.CreateModel(
            name='WatoneExportIpTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExportAddsegment', models.CharField(max_length=40, verbose_name='出口地址')),
                ('Province', models.CharField(max_length=40, verbose_name='省份')),
                ('City', models.CharField(max_length=40, verbose_name='城市')),
                ('AccessOperator', models.CharField(max_length=40, verbose_name='接入运营商')),
                ('BackboneTransmission', models.CharField(max_length=40, verbose_name='骨干传输')),
                ('ASNumber', models.IntegerField(blank=True, null=True, verbose_name='AS号')),
                ('Remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('NetworkType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPaddrmanagement.NetTypeTable', verbose_name='网络类型')),
            ],
            options={
                'verbose_name': '华通出口地址列表',
                'verbose_name_plural': '华通出口地址列表',
                'ordering': ['ExportAddsegment'],
            },
        ),
        migrations.AddField(
            model_name='backtosounceexporttable',
            name='NetworkType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPaddrmanagement.NetTypeTable', verbose_name='网络类型'),
        ),
        migrations.AlterUniqueTogether(
            name='watoneexportiptable',
            unique_together={('ExportAddsegment',)},
        ),
        migrations.AlterUniqueTogether(
            name='internetresoucestatble',
            unique_together={('InternetAddsegment',)},
        ),
        migrations.AlterUniqueTogether(
            name='cdnmanagementiptable',
            unique_together={('ManagementIp',)},
        ),
    ]
