# Generated by Django 2.0.1 on 2018-01-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=40, verbose_name='姓名')),
                ('FileName', models.FileField(upload_to='./useruploadfile/', verbose_name='文件名')),
                ('TableName', models.CharField(max_length=30, verbose_name='操作对象')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '用户上传文件',
                'verbose_name_plural': '用户上传文件',
                'ordering': ['UserName'],
            },
        ),
    ]
